name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SITE_HOST: 91.226.81.209
  SITE: wiki.darpru.pro

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
       hugo-version: 'latest'
       extended: true
        
    - name: Build
      run: hugo
      
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --chown=www-data:www-data 
        path: ./public/.
        remote_path: /var/www/${{env.SITE}}/htdocs
        remote_host:  ${{env.SITE_HOST}}
        remote_user: root
        remote_key: ${{ secrets.DEPLOY_KEY }}
